### ISSUE TITLE
可以用docker容器挂这个吗？

### ISSUE THREAD

**Issue by lpxtennan** [leeyiding/get_CCB#12]
可以用docker挂吗？

**Comment by 546220777** [comment]
> 可以用docker挂吗？

可以

**Comment by lpxtennan** [comment]
> > 可以用docker挂吗？
> 
> 可以

怎么挂？大佬求教程

**Comment by lxr760** [comment]
> > 可以用docker挂吗？
> 
> 可以

求问哪个docker环境带python

**Comment by Shawn1eong** [comment]
自己随便装个Python的容器不就好了。问这种问题，谁会回答
