### ISSUE TITLE
大佬CCB求个群，CCB那个调用接口失败！

### ISSUE THREAD

**Issue by lovecomic** [leeyiding/get_CCB#18]
大佬CCB求个群，CCB那个调用接口失败！

**Comment by lovecomic** [comment]
求修复！求更新！

**Comment by leeyiding** [comment]
号已黑，心有余而力不足

**Comment by lovecomic** [comment]
换个号继续搞啊，我每天用没黑啊.....大佬求个群

**Comment by lovecomic** [comment]
换个号继续搞啊，我每天用没黑啊.....大佬求个群


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leeyiding/get_CCB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leeyiding/get_CCB] 大佬CCB求个群，CCB那个调用接口失败！ (#18)





 
号已黑，心有余而力不足

**Comment by leeyiding** [comment]
https://t.me/joinchat/jNNCJSBp8o5hMGM1

**Comment by lovecomic** [comment]
没QQ群或微信群吗 这个貌似要翻墙啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leeyiding/get_CCB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leeyiding/get_CCB] 大佬CCB求个群，CCB那个调用接口失败！ (#18)





 
https://t.me/joinchat/jNNCJSBp8o5hMGM1

**Comment by leeyiding** [comment]
无

**Comment by shusheng110** [comment]
> https://t.me/joinchat/jNNCJSBp8o5hMGM1
大佬 链接失效了啊~~能给个新的链接吗

**Comment by leeyiding** [comment]
> > https://t.me/joinchat/jNNCJSBp8o5hMGM1
> > 大佬 链接失效了啊~~能给个新的链接吗

https://t.me/joinchat/ppJzmBeFcl1mOTQ1
有效期一天

**Comment by shusheng110** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leeyiding/get_CCB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月10日(星期六) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leeyiding/get_CCB] 大佬CCB求个群，CCB那个调用接口失败！ (#18)





   
https://t.me/joinchat/jNNCJSBp8o5hMGM1
 大佬 链接失效了啊~~能给个新的链接吗
   
https://t.me/joinchat/ppJzmBeFcl1mOTQ1
 有效期一天
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.







大佬····我周末没看到能麻烦再发一次嘛···又失效了！！抱歉了

**Comment by leeyiding** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "leeyiding/get_CCB" ***@***.***&gt;; 发送时间:&nbsp;2021年7月10日(星期六) 晚上10:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [leeyiding/get_CCB] 大佬CCB求个群，CCB那个调用接口失败！ (#18) https://t.me/joinchat/jNNCJSBp8o5hMGM1 大佬 链接失效了啊~~能给个新的链接吗 https://t.me/joinchat/ppJzmBeFcl1mOTQ1 有效期一天 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 大佬····我周末没看到能麻烦再发一次嘛···又失效了！！抱歉了

最新链接重新激活了

**Comment by baozi-cc** [comment]
> > ------------------ 原始邮件 ------------------ 发件人: "leeyiding/get_CCB" _**@**_._**>; 发送时间: 2021年7月10日(星期六) 晚上10:25 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [leeyiding/get_CCB] 大佬CCB求个群，CCB那个调用接口失败！ (#18) https://t.me/joinchat/jNNCJSBp8o5hMGM1 大佬 链接失效了啊~~能给个新的链接吗 https://t.me/joinchat/ppJzmBeFcl1mOTQ1 有效期一天 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 大佬····我周末没看到能麻烦再发一次嘛···又失效了！！抱歉了
> 
> 最新链接重新激活了

大佬，还能进吗，我也想进

**Comment by jeantoe3** [comment]
大佬，tg还能进吗

**Comment by mfcer110** [comment]
老哥再发下飞机群吧  更新财富小镇了  感谢

**Comment by sanwan2009** [comment]
大佬申请进TG群。

**Comment by ghqaz3633** [comment]
大佬，没tg怎么搞啊，现在都没法注册tg了

**Comment by bozins** [comment]
老哥，求个最新财富的PY，私个TG群也可以啊

**Comment by leeyiding** [comment]
统一回复，自从上次封号，新的财富季依旧没有解封，故无新脚本产出。
