### ISSUE TITLE
总是报转码错误

### ISSUE THREAD

**Issue by xukf2000** [leeyiding/get_CCB#4]
![image](https://user-images.githubusercontent.com/34463908/117530847-efdb6e80-b011-11eb-981f-17b7d1659fc5.png)
你好，我开头加了#coding=utf-8  也不行，加了以后运行了但是后面又不跑了，是我的环境变量问题吗？
![image](https://user-images.githubusercontent.com/34463908/117530866-100b2d80-b012-11eb-8ca7-dc0eff5f2ab5.png)

**Comment by leeyiding** [comment]
@xukf2000 请使用Python3运行脚本

**Comment by xukf2000** [comment]
好的 可以了 谢谢
