### ISSUE TITLE
获取['nickname']错误，是否增加try判断？

### ISSUE THREAD

**Issue by Crazyguy2020** [leeyiding/get_CCB#8]
![Screenshot_20210512-105854](https://user-images.githubusercontent.com/49531214/117912112-74c7d000-b311-11eb-9cae-3fefcf2ccf73.jpg)

账号没有昵称，程序每次跑到这里报错停止了。
是否可增加try一个判断？

**Comment by leeyiding** [comment]
不是用户名影响的，由于活动接口繁忙导致的，新版本已优化
